# Generated by Django 4.0.3 on 2022-05-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cve',
            fields=[
                ('cve_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('titre', models.TextField(null=True)),
                ('date_publication', models.TextField(null=True)),
                ('date_modification', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('cvss2_vector_string', models.TextField(null=True)),
                ('cvss2_access_vector', models.TextField(null=True)),
                ('cvss2_access_complexity', models.TextField(null=True)),
                ('cvss2_authentication', models.TextField(null=True)),
                ('cvss2_confidentiality_impact', models.TextField(null=True)),
                ('cvss2_integrity_impact', models.TextField(null=True)),
                ('cvss2_availibility_impact', models.TextField(null=True)),
                ('cvss2_score', models.IntegerField(null=True)),
                ('cvss2_sevirity', models.TextField(null=True)),
                ('cvss2_exploit_score', models.IntegerField(null=True)),
                ('cvss2_impact_score', models.IntegerField(null=True)),
                ('cvss2_obtain_all_priv', models.BooleanField(null=True)),
                ('cvss2_obtain_user_priv', models.BooleanField(null=True)),
                ('cvss2_obtain_other_priv', models.BooleanField(null=True)),
                ('cvss2_user_interaction', models.BooleanField(null=True)),
                ('cvss3_vector_string', models.TextField(null=True)),
                ('cvss3_attack_vector', models.TextField(null=True)),
                ('cvss3_attack_complexity', models.TextField(null=True)),
                ('cvss3_priv_required', models.TextField(null=True)),
                ('cvss3_user_interaction', models.TextField(null=True)),
                ('cvss3_scope', models.TextField(null=True)),
                ('cvss3_sevirity', models.TextField(null=True)),
                ('cvss3_confidentiality_impact', models.TextField(null=True)),
                ('cvss3_integrity_impact', models.TextField(null=True)),
                ('cvss3_availibility_impact', models.TextField(null=True)),
                ('cvss3_score', models.IntegerField(null=True)),
                ('cvss3_exploit_score', models.IntegerField(null=True)),
                ('cvss3_impact_score', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'cve',
            },
        ),
        migrations.CreateModel(
            name='cwe',
            fields=[
                ('cwe_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cwe',
            },
        ),
        migrations.CreateModel(
            name='entreprise',
            fields=[
                ('nom_en', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('secteur_activité_en', models.TextField(null=True)),
                ('url_en', models.TextField(null=True)),
                ('email_en', models.TextField(null=True)),
                ('num_tel_en', models.TextField(null=True)),
                ('date_ajout_en', models.TextField(null=True)),
                ('address_en', models.TextField(null=True)),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(null=True)),
                ('tag_exploit', models.IntegerField(null=True)),
                ('tag_patch', models.IntegerField(null=True)),
                ('tag_mitigation', models.IntegerField(null=True)),
                ('tag_third_party_advisory', models.IntegerField(null=True)),
                ('tag_vendor_advisory', models.IntegerField(null=True)),
                ('cve_id', models.ForeignKey(db_column='cve_id', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.cve')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe', models.TextField(null=True)),
                ('cpe_minimal', models.TextField(null=True)),
                ('vendor', models.TextField(null=True)),
                ('product', models.TextField(null=True)),
                ('version', models.TextField(null=True)),
                ('cve_id', models.ForeignKey(db_column='cve_id', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.cve')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='cve_cwe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.ForeignKey(db_column='cve_id', on_delete=django.db.models.deletion.DO_NOTHING, to='CVE_BD.cve')),
                ('cwe_id', models.ForeignKey(db_column='cwe_id', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.cwe')),
            ],
            options={
                'db_table': 'cve_cwe',
            },
        ),
        migrations.CreateModel(
            name='actifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_actif', models.TextField(null=True)),
                ('nom_vendor', models.TextField(null=True)),
                ('version_actif', models.TextField(null=True)),
                ('type_actif', models.TextField(null=True)),
                ('os_actif', models.TextField(null=True)),
                ('cpe_actif', models.TextField(null=True)),
                ('importance_actif', models.TextField(null=True)),
                ('date_ajout_actif', models.TextField(null=True)),
                ('new_cpe_actif', models.TextField(null=True)),
                ('nom_en', models.ForeignKey(db_column='nom_en', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.entreprise')),
            ],
            options={
                'db_table': 'actifs',
            },
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('cve_id', 'reference'), name='cve_ref'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('cpe', 'cve_id'), name='cpecve'),
        ),
        migrations.AddConstraint(
            model_name='cve_cwe',
            constraint=models.UniqueConstraint(fields=('cve_id', 'cwe_id'), name='cvecwe_unique'),
        ),
    ]
