# Generated by Django 4.0.3 on 2022-05-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pour_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entreprise', models.TextField(null=True)),
                ('cpe', models.TextField(null=True)),
                ('affected', models.BooleanField(null=True)),
                ('cve_id', models.ForeignKey(db_column='cve_id', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.cve')),
            ],
            options={
                'db_table': 'pour_asset',
            },
        ),
    ]
