# Generated by Django 4.0.3 on 2022-05-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0002_pour_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='notif',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_actif', models.TextField(null=True)),
                ('checked', models.BooleanField(null=True)),
                ('cve_id', models.ForeignKey(db_column='cve_id', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.cve')),
                ('id_ajout', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.actifs')),
                ('nom_en', models.ForeignKey(db_column='nom_en', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.entreprise')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
