# Generated by Django 4.0.3 on 2022-05-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CVE_BD', '0003_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='num_tel_en',
        ),
        migrations.CreateModel(
            name='employe',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.TextField(null=True)),
                ('prenom', models.TextField(null=True)),
                ('num_tel', models.TextField(null=True)),
                ('job_title', models.TextField(null=True)),
                ('date_ajout_en', models.TextField(null=True)),
                ('nom_entreprise', models.ForeignKey(db_column='nom_en', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.entreprise')),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employe',
            },
        ),
    ]
