# Generated by Django 4.0.3 on 2022-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0005_rename_date_ajout_en_employe_date_ajout_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='date_ajout',
            field=models.TextField(null=True),
        ),
    ]
