# Generated by Django 4.0.3 on 2022-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0007_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='colonne',
            field=models.IntegerField(null=True),
        ),
    ]
