# Generated by Django 4.0.3 on 2022-05-29 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CVE_BD', '0009_workflow_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_admin',
            fields=[
                ('id_notif_admin', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('checked', models.BooleanField(null=True)),
                ('email_id', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.employe')),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_admin',
            },
        ),
    ]
