# Generated by Django 4.0.3 on 2022-05-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0010_notification_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_admin',
            name='email_id',
        ),
    ]
