# Generated by Django 4.0.3 on 2022-05-31 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0013_pour_asset_delete_not_affected_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pour_asset',
            name='id_entreprise',
        ),
        migrations.AddField(
            model_name='pour_asset',
            name='nom_en',
            field=models.ForeignKey(db_column='nom_en', default='lesi', on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.entreprise'),
        ),
    ]
