# Generated by Django 4.0.3 on 2022-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0014_remove_pour_asset_id_entreprise_pour_asset_nom_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='date_modif_statut',
            field=models.TextField(null=True),
        ),
    ]
