# Generated by Django 4.0.3 on 2022-06-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0015_employe_date_modif_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='actif_products',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.product')),
                ('id_actif_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CVE_BD.actifs')),
            ],
            options={
                'db_table': 'actif_products',
            },
        ),
    ]
