# Generated by Django 4.0.3 on 2022-06-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0016_actif_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actif_products',
        ),
    ]
