# Generated by Django 4.0.3 on 2022-06-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0018_actif_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actifs',
            name='cpe_actif',
        ),
        migrations.RemoveField(
            model_name='actifs',
            name='os_actif',
        ),
        migrations.RemoveField(
            model_name='actifs',
            name='type_actif',
        ),
    ]
