# Generated by Django 4.0.5 on 2022-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVE_BD', '0019_remove_actifs_cpe_actif_remove_actifs_os_actif_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product', 'vendor', 'version'], name='product_product_ebdea2_idx'),
        ),
    ]
